-- Add new columns to TBL_SALES_LEADS
ALTER TABLE [dbo].[TBL_SALES_LEADS] ADD
  SHIPPER_ADDRESS      NVARCHAR(1000) NULL,
  CONSIGNEE_ADDRESS    NVARCHAR(1000) NULL,
  CONSIGNEE_WEBSITE    NVARCHAR(500)  NULL,
  MODE_OF_TRANSPORT    NVARCHAR(100)  NULL,
  ORIGIN_PORT          NVARCHAR(255)  NULL,
  DEST_PORT            NVARCHAR(255)  NULL,
  COMMODITY            NVARCHAR(2000) NULL,
  HS_CODE              NVARCHAR(100)  NULL,
  SPECIAL_REQUIREMENTS NVARCHAR(2000) NULL,
  RATE_FCL             NVARCHAR(500)  NULL,
  RATE_LCL             NVARCHAR(500)  NULL,
  RATE_VALIDITY        NVARCHAR(255)  NULL;
