-- Total INSERT rows: 71

-- ================================================================
-- ONE (Ocean Network Express) — Kattupalli EUR + MED Rates
-- Validity: 16-31 May 2026 | Vessel basis
-- Origin: Kattupalli (INKAT)
-- EUROPE: Incl CAF,CSS,HEA,MBS | Extra: OBS $117 EES $95 EFS $120 ESD $35 SLF THC Docs
-- MED:    Incl CAF,CSS,MBS      | Extra: OBS $119 EES $182 EFS $120 ESD $35 HEA THC Docs
-- Note: EES not applicable for UK ports
-- Note: 40'HQ rate stored as RATE_40; where 40GP differs, noted in NOTES
-- ================================================================

USE [manilal];
GO

-- ======== EUROPE (16-31 May 2026) ========

-- North Europe hubs (shared rate: 1630/1365)
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Belgium','ANTWERP','USD',1630,1365,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Germany','HAMBURG','USD',1630,1365,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Netherlands','ROTTERDAM','USD',1630,1365,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','UK','SOUTHAMPTON','USD',1630,1365,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EFS $120/teu; ESD $35/BL; EES N/A (UK); SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Denmark
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Denmark','AAHUS','USD',2130,1915,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Denmark','AALBORG','USD',2055,1940,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Denmark','AARHUS','USD',1830,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Denmark','COPENHAGEN','USD',1830,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Denmark','FREDERICIA','USD',1830,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Norway
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Norway','BERGEN','USD',2430,2865,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Norway','FREDRIKSTAD','USD',2355,2365,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Norway','KRISTIANSAND S.','USD',2380,2565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Norway','LARVIK','USD',2330,2490,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Sweden
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','GAVLE','USD',1930,1815,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY; 40GP=$1915','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','GOTHENBURG','USD',1680,1465,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','HELSINGBORG','USD',1830,1615,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','NORRKOPING','USD',2880,3015,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','SODERTALJE','USD',2080,2065,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Sweden','STOCKHOLM','USD',2830,3065,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Finland
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Finland','HELSINKI','USD',1780,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Finland','KOTKA','USD',1780,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Finland','OULU','USD',2990,2965,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY; 40GP=$3565','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Finland','RAUMA','USD',1780,1565,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Baltic States
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Lithuania','KLAIPEDA','USD',1880,1665,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Latvia','RIGA','USD',1880,1665,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Estonia','TALLINN','USD',1880,1665,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Poland
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Poland','GDANSK','USD',1680,1465,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Poland','GDYNIA','USD',1680,1465,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- France
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','France','LE HAVRE (SEINE-MARITIME)','USD',1680,1465,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Portugal
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Portugal','LEIXOES','USD',1780,1665,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Portugal','LISBON','USD',1780,1665,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- UK (EES not applicable)
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','UK','BELFAST','USD',2330,1815,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EFS $120/teu; ESD $35/BL; EES N/A (UK); SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','UK','GRANGEMOUTH (FALKIRK)','USD',2130,2045,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EFS $120/teu; ESD $35/BL; EES N/A (UK); SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','UK','IMMINGHAM (LINCOLNSHIRE)','USD',2130,2165,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EFS $120/teu; ESD $35/BL; EES N/A (UK); SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','UK','TEESPORT (NORTH YORKSHIRE)','USD',2130,2045,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EFS $120/teu; ESD $35/BL; EES N/A (UK); SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Ireland
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Ireland','CORK','USD',2030,1815,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Ireland','DUBLIN','USD',2030,1815,'2026-05-16','2026-05-31',NULL,'OBS:117/teu;EES:95/teu;EFS:120/teu;ESD:35/bl;SLF:collect;THC:collect;CAF:incl;CSS:incl;HEA:incl;MBS:incl','Incl CAF,CSS,HEA,MBS; OBS $117/teu; EES $95/teu (not UK); EFS $120/teu; ESD $35/BL; SLF+THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | Europe rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, HEA, MBS|Sub to: OBS USD 117/TEU | EFS USD 120/TEU | EES USD 95/TEU (not applicable UK ports)|ESD USD 35/BL | SLF applicable | THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- ======== MED (16-31 May 2026) ========

-- Spain
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','ALGECIRAS','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','BARCELONA','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','BILBAO','USD',2190,2285,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','GIJON','USD',2190,2285,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','VALENCIA','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Spain','VIGO','USD',2190,2285,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- France
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','France','FOS-SUR-MER (BOUCHES DU RHONE)','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Italy
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','ANCONA','USD',1990,1885,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','GENOA','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','LA SPEZIA','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','LIVORNO','USD',2140,2185,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','RAVENNA','USD',2340,2485,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','TRIESTE','USD',2390,2585,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Italy','VENICE','USD',2040,1985,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Greece
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Greece','PIRAEUS','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Greece','THESSALONIKI','USD',2040,1985,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Turkey
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Turkey','GEMLIK','USD',2190,2285,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Turkey','ISKENDERUN','USD',2040,1985,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Turkey','ISTANBUL','USD',1990,1885,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Turkey','IZMIT','USD',1990,1885,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Turkey','MERSIN','USD',1990,1885,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Israel
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Israel','ASHDOD','USD',2140,2185,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Israel','HAIFA','USD',2140,2185,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Egypt
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Egypt','ALEXANDRIA','USD',2040,1985,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Egypt','DAMIETTA','USD',1940,1785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Adriatic / Balkans
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Slovenia','KOPER','USD',1990,1885,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Croatia','RIJEKA','USD',2390,2685,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Albania','DURRES','USD',2450,2450,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Bulgaria / Romania
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Bulgaria','BOURGAS','USD',2440,2785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Bulgaria','VARNA','USD',2440,2785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Romania','CONSTANTA','USD',2440,2785,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Lebanon
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Lebanon','BEIRUT','USD',2090,2085,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Morocco
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Morocco','CASABLANCA','USD',3850,5240,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','KATTUPALLI','Morocco','TANGIER','USD',3350,4240,'2026-05-16','2026-05-31',NULL,'OBS:119/teu;EES:182/teu;EFS:120/teu;ESD:35/bl;HEA:300/20D>16mt-600/20D>18mt;THC:collect;CAF:incl;CSS:incl;MBS:incl','Incl CAF,CSS,MBS; OBS $119/teu; EES $182/teu; EFS $120/teu; ESD $35/BL; HEA $300/20D>16MT or $600/20D>18MT extra; THC+Docs extra; CY/CY','ONE (Ocean Network Express) | Kattupalli origin | MED rates|Validity: 16-31 May 2026 (vessel basis; Gate In date)|Rates inclusive of: CAF, CSS, MBS|Sub to: OBS USD 119/TEU | EFS USD 120/TEU | EES USD 182/TEU|ESD USD 35/BL | HEA USD 300/20''D (cargo wt > 16 MT); USD 600/20''D (cargo wt > 18 MT)|THC both ends | Docs charges extra|Rates CY/CY basis | Standard Tariff F/T at POD based on vessel sailing date|Multiple containers: last container gate-in date used for rate application|THC/Haulage: https://in.one-line.com/standard-page/local-tariffs-and-surcharges|Surcharges: https://ecomm.one-line.com/ecom/CUP_HOM_3116.do?sessLocale=en','https://in.one-line.com/standard-page/local-tariffs-and-surcharges',1,'SYSTEM',GETDATE(),GETDATE());
GO

