-- Total INSERT rows: 6

-- ============================================================
-- ONE (Ocean Network Express) - Europe & MED Rates Apr 2H 2026
-- Validity: 22-30 Apr 2026 (NSA Handover / Gate In date)
-- Origin: Nhava Sheva | Route: IOX (Europe) / IOM (MED)
-- Inclusive: EBS, ISPS, PSS, ECA (Europe only)
-- Surcharges extra: OBS, EES, SLF, EFS, ESD, THC, BL, HEA
-- HEA: $300/20GP >=16T (Europe/MED); $600/20GP >=18T (MED)
-- FGP: $100/cntr food grade only
-- DET freetime: $50/TEU for 14-day detention at destination
-- ============================================================

USE [manilal];
GO

-- ======== EUROPE (IOX service) - AMS / HAM / RTM ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Netherlands','ROTTERDAM','USD',1735,1460,'2026-04-22','2026-04-30',NULL,'OBS:117/teu;EES:95/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS/ECA; OBS $117/teu; EES $95/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOX service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Belgium','ANTWERP','USD',1735,1460,'2026-04-22','2026-04-30',NULL,'OBS:117/teu;EES:95/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS/ECA; OBS $117/teu; EES $95/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOX service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Germany','HAMBURG','USD',1735,1460,'2026-04-22','2026-04-30',NULL,'OBS:117/teu;EES:95/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS/ECA; OBS $117/teu; EES $95/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOX service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());

-- ======== MED (IOM service) - BCN / VLC / GOA ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Spain','BARCELONA','USD',2025,1755,'2026-04-22','2026-04-30',NULL,'OBS:119/teu;EES:182/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS (no ECA); OBS $119/teu; EES $182/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOM service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Spain','VALENCIA','USD',2025,1755,'2026-04-22','2026-04-30',NULL,'OBS:119/teu;EES:182/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS (no ECA); OBS $119/teu; EES $182/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOM service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('ONE','India','NHAVA SHEVA','Italy','GENOVA','USD',2025,1755,'2026-04-22','2026-04-30',NULL,'OBS:119/teu;EES:182/teu;SLF:10/cntr;EFS:160/teu;ESD:35/bl;THC:collect;BL:collect;HEA:collect','Incl EBS/ISPS/PSS (no ECA); OBS $119/teu; EES $182/teu; SLF $10; EFS $160/teu; ESD $35/BL; THC+BL+HEA extra; IOM service','FAK CY/CY non-haz rates; Freight prepaid|Rates incl EBS/ISPS/PSS/ECA (ECA for Europe only)|HEA: USD 300/20GP (net wt >= 16T, Europe/MED); USD 600/20GP (net wt >= 18T, MED only)|USD 50/TEU for 14 days freetime detention at destination|FGP USD 100/cntr for food grade containers only|DET/booking cancellation charges apply for returned/empty offloaded containers|Rates applicable as per Gate In date of container|Sub to inventory and space availability|IOX-Europe / IOM-MED service via ONE-LINE|https://www.one-line.com/en/advanced-page/one-quote',1,'SYSTEM',GETDATE(),GETDATE());

