-- Total INSERT rows: 75

-- ================================================================
-- PIL (India) Pvt. Ltd. — NHAVA SHEVA Rates June 2026
-- FAR EAST: valid 01-30 Jun 2026 | Incl EBS | +Seal $10 SFF $15 THC
-- RED SEA:  valid 01-14 Jun 2026 | Incl EBS | +Seal $10 SFF $15 THC
-- NZ:       valid 01-14 Jun 2026 | Incl EBS | +Seal $10 SFF $15 THC
-- AUS: NOT ACCEPTING 1st half June (space constraint) — SKIPPED
-- Where 20ft > 40ft: stored as-is from source sheet
-- ================================================================

USE [manilal];
GO

-- ======== FAR EAST (01-30 Jun 2026) ========

-- China — Major direct ports
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHANGHAI','USD',41,81,'2026-06-01','2026-06-30',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHEKOU','USD',41,81,'2026-06-01','2026-06-30',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NINGBO','USD',41,81,'2026-06-01','2026-06-30',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Singapore
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANSHA','USD',65,105,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','XINGANG','USD',115,180,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','QINGDAO','USD',90,205,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','QINZHOU','USD',165,255,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Shanghai
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YANGZHOU','USD',65,105,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANTONG','USD',65,480,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUHU','USD',65,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUHAN','USD',65,205,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YICHANG','USD',65,330,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YUE YANG','USD',90,230,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANJING','USD',65,105,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','CHONGQING','USD',215,580,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','LIANYUNGANG','USD',90,180,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','HUANGSHI','USD',340,230,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','CHANGSHA','USD',340,330,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Ningbo
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FUZHOU (MAWEI)','USD',315,380,'2026-06-01','2026-06-30','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FUZHOU (JIANGYIN)','USD',90,780,'2026-06-01','2026-06-30','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WENZHOU','USD',90,180,'2026-06-01','2026-06-30','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Shekou
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','HUANGPU (GCT)','USD',190,105,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SANSHAN','USD',240,430,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SANSHUI','USD',65,105,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUZHOU','USD',140,430,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','JIUJIANG','USD',90,180,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YUNFU','USD',215,330,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FANGCHENG','USD',315,455,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHANTOU','USD',140,230,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','ZHANJIANG','USD',315,130,'2026-06-01','2026-06-30','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Japan (via Shanghai; 20ft > 40ft on source sheet)
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','TOKYO','USD',615,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','YOKOHAMA','USD',565,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','NAGOYA','USD',490,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','KOBE','USD',415,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','OSAKA','USD',415,130,'2026-06-01','2026-06-30','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Taiwan
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Taiwan','KAOHSIUNG','USD',390,90,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- South Korea
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','South Korea','PUSAN','USD',65,330,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','South Korea','INCHEON','USD',440,805,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Thailand
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Thailand','LAEM CHA BANG','USD',65,105,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Thailand','BANGKOK (PAT)','USD',65,105,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Malaysia — direct and via Port Klang West
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PORT KLANG (WEST)','USD',41,81,'2026-06-01','2026-06-30',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PENANG','USD',315,105,'2026-06-01','2026-06-30','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PASIR GUDANG','USD',65,580,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','SANDAKAN','USD',765,780,'2026-06-01','2026-06-30','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','TAWAU','USD',740,855,'2026-06-01','2026-06-30','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','BINTULU','USD',340,730,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','LABUAN','USD',890,1155,'2026-06-01','2026-06-30','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','SIBU','USD',390,1080,'2026-06-01','2026-06-30','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','KUCHING','USD',790,1405,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','KOTA KINABALU','USD',565,1605,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Brunei
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Brunei','MUARA','USD',790,1280,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Singapore
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Singapore','SINGAPORE','USD',41,81,'2026-06-01','2026-06-30',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Vietnam
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','HAIPHONG','USD',65,780,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','HO CHI MINH (CAT LAI)','USD',65,105,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','QUI NHON','USD',90,280,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Cambodia
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Cambodia','SIHANOUKVILLE','USD',615,1055,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Myanmar
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Myanmar','YANGON','USD',615,1055,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Indonesia
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','JAKARTA','USD',540,630,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','SURABAYA','USD',315,580,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','BELAWAN','USD',65,105,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','SEMARANG','USD',515,755,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Philippines
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','MANILA NORTH','USD',665,980,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','GENERAL SANTOS','USD',615,730,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','SUBIC BAY','USD',665,1180,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','DAVAO','USD',565,980,'2026-06-01','2026-06-30','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-30 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- ======== RED SEA (01-14 Jun 2026) ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Djibouti','DJIBOUTI','USD',3850,5300,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Saudi Arabia','JEDDAH','USD',3900,5400,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Egypt','AIN SOKHNA','USD',3700,5000,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Jordan','AQABA','USD',3800,5200,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Sudan','PORT SUDAN','USD',5100,6500,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','via Singapore/Jeddah','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Yemen','ADEN','USD',5100,6500,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','via Singapore/Jeddah','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Yemen','HODEIDAH','USD',7700,11860,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','via Singapore/Djibouti','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Somalia','BERBERA','USD',5100,6500,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','via Singapore/Djibouti','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Red Sea rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- ======== AUSTRALIA — NOT ACCEPTING 1st half June (space constraint) ========
-- Sydney/Brisbane/Melbourne and Fremantle/Adelaide: no rates offered

-- ======== NEW ZEALAND (01-14 Jun 2026) ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','New Zealand','AUCKLAND / NAPIER / LYTTELTON','USD',875,1650,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | New Zealand rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','New Zealand','WELLINGTON / TAURANGA','USD',875,1650,'2026-06-01','2026-06-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | New Zealand rates|Validity: 01-14 Jun 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

