-- Total INSERT rows: 67

-- ================================================================
-- PIL (India) Pvt. Ltd. — NHAVA SHEVA Rates July 2026
-- FAR EAST: valid 01-31 Jul 2026 | Incl EBS | +Seal $10 SFF $15 THC
-- RED SEA:  NOT ACCEPTING 1st half July (2nd leg space constraint) — SKIPPED, no rates on sheet
-- AUSTRALIA: valid 01-14 Jul 2026 | Incl EBS (NOW OFFERED — was 'not accepting' in June)
-- NZ:       valid 01-14 Jul 2026 | Incl EBS
-- Where 20ft > 40ft: stored as-is from source sheet
-- ================================================================

USE [manilal];
GO

-- ======== FAR EAST (01-31 Jul 2026) ========

-- China — Major direct ports
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHANGHAI','USD',41,81,'2026-07-01','2026-07-31',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHEKOU','USD',41,81,'2026-07-01','2026-07-31',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NINGBO','USD',41,81,'2026-07-01','2026-07-31',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Singapore
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANSHA','USD',65,305,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','XINGANG','USD',65,280,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','QINGDAO','USD',115,380,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','QINZHOU','USD',115,455,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Shanghai
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YANZHOU','USD',65,130,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANTONG','USD',290,730,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUHU','USD',65,130,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUHAN','USD',65,205,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YICHANG','USD',65,355,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YUE YANG','USD',340,255,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','NANJING','USD',65,130,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','CHONGQING','USD',140,630,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','LIANYUNGANG','USD',265,180,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','HUANGSHI','USD',340,255,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','CHANGSHA','USD',365,330,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Ningbo
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FUZHOU (MAWEI)','USD',490,455,'2026-07-01','2026-07-31','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FUZHOU (JIANGYIN)','USD',140,1030,'2026-07-01','2026-07-31','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WENZHOU','USD',90,180,'2026-07-01','2026-07-31','NINGBO','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- China — via Shekou
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','HUANGPU (GCT)','USD',190,480,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SANSHAN','USD',265,555,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SANSHUI','USD',65,105,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','WUZHOU','USD',240,580,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','JIUJIANG','USD',90,180,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','YUNFU','USD',240,505,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','FANGCHENG','USD',265,580,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','SHANTOU','USD',140,230,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','China','ZHANJIANG','USD',365,130,'2026-07-01','2026-07-31','SHEKOU','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Japan (via Shanghai; 20ft > 40ft on source sheet) — no Kobe rate this period
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','TOKYO','USD',490,255,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','YOKOHAMA','USD',440,180,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','NAGOYA','USD',490,455,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Japan','OSAKA','USD',315,180,'2026-07-01','2026-07-31','SHANGHAI','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Taiwan
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Taiwan','KAOHSIUNG','USD',315,105,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect','20ft>40ft on source sheet','PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- South Korea
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','South Korea','PUSAN','USD',90,405,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','South Korea','INCHEON','USD',515,955,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Thailand
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Thailand','LAEM CHA BANG','USD',65,255,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Thailand','BANGKOK (PAT)','USD',65,180,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Malaysia — direct and via Port Klang West
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PORT KLANG (WEST)','USD',41,81,'2026-07-01','2026-07-31',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PENANG','USD',65,255,'2026-07-01','2026-07-31','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','PASIR GUDANG','USD',65,730,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','SANDAKAN','USD',890,1680,'2026-07-01','2026-07-31','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','TAWAU','USD',890,1680,'2026-07-01','2026-07-31','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','BINTULU','USD',890,1680,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','KUCHING','USD',840,1680,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','LABUAN','USD',890,1680,'2026-07-01','2026-07-31','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','SIBU','USD',540,1480,'2026-07-01','2026-07-31','PORT KLANG WEST','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Malaysia','KOTA KINABALU','USD',890,1680,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Brunei
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Brunei','MUARA','USD',890,1680,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Singapore
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Singapore','SINGAPORE','USD',41,81,'2026-07-01','2026-07-31',NULL,'EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Vietnam
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','HAIPHONG','USD',65,780,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','HO CHI MINH (CAT LAI)','USD',65,255,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Vietnam','QUI NHON','USD',115,455,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Indonesia
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','JAKARTA','USD',390,780,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','SURABAYA','USD',65,805,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','BELAWAN','USD',65,255,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Indonesia','SEMARANG','USD',515,980,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Philippines — no General Santos rate this period
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','MANILA NORTH','USD',540,1105,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','SUBIC BAY','USD',665,1455,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Philippines','DAVAO','USD',540,1130,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Cambodia
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Cambodia','SIHANOUKVILLE','USD',515,1180,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- Myanmar
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Myanmar','YANGON','USD',440,1130,'2026-07-01','2026-07-31','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Far East rates|Validity: 01-31 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Rates can be negotiated for PODs marked in RED on source sheet|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- ======== RED SEA — NOT ACCEPTING 1st half July (2nd leg space constraint) ========
-- No rate figures given on source sheet for Djibouti/Jeddah/Ain Sokhna/Aqaba/
-- Port Sudan/Aden/Hodeidah/Berbera — all skipped, no INSERT rows for Red Sea

-- ======== AUSTRALIA (01-14 Jul 2026) — now offered (was 'not accepting' in June) ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Australia','SYDNEY / BRISBANE / MELBOURNE','USD',1075,2100,'2026-07-01','2026-07-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Australia rates|Validity: 01-14 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','Australia','FREMANTLE / ADELAIDE','USD',1075,2100,'2026-07-01','2026-07-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | Australia rates|Validity: 01-14 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

-- ======== NEW ZEALAND (01-14 Jul 2026) ========

INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','New Zealand','AUCKLAND / NAPIER / LYTTELTON','USD',850,1600,'2026-07-01','2026-07-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | New Zealand rates|Validity: 01-14 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO
INSERT INTO [dbo].[FREIGHT_RATES] (SHIPPING_LINE,ORIGIN_COUNTRY,ORIGIN_PORT,DEST_COUNTRY,DEST_PORT,CURRENCY,RATE_20,RATE_40,VALID_FROM,VALID_TO,VIA_PORT,SURCHARGES,NOTES,CLAUSES,PDF_URL,IS_ACTIVE,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PIL','India','NHAVA SHEVA','New Zealand','WELLINGTON / TAURANGA','USD',850,1600,'2026-07-01','2026-07-14','SINGAPORE','EBS:incl;Seal:10/ctr;SFF:15/BL;THC:collect',NULL,'PIL (India) Pvt. Ltd. | Nhava Sheva origin | New Zealand rates|Validity: 01-14 Jul 2026|Rates inclusive of: EBS|Subject to: Seal USD 10/container | SFF USD 15/BL | THC + local charges both ends|Space and equipment subject to availability','https://www.pilship.com/en/index.html',1,'SYSTEM',GETDATE(),GETDATE());
GO

